### ISSUE TITLE
DomainBed results with "oracle" model selection

### ISSUE THREAD

**Issue by alexrame** [YugeTen/fish#1]
Congratulations for this really interesting work.
I was wondering whether you could provide the DomainBed results, but with the best hyper-parameter chosen on a validation dataset from the test domain (i.e the oracle model selection).
That would be of great help to include your paper as a new comparable approach in upcoming papers.
Best regards
Alexandre

**Comment by YugeTen** [comment]
Hi Alexandre, thank you for your suggestion! I'll look into this.
