### ISSUE TITLE
Domain Sampling Issue during Reproducing Results in Civil

### ISSUE THREAD

**Issue by LFhase** [YugeTen/fish#3]
Hi fish authors, 

Thanks for the nice work! 

However, when I was trying to reproduce results in `civilcomments` using the current code, it seems there was a bug regarding `sample_domains` in `train_fish`. Specifically, a RuntimeError was encountered in `get_batch` and it's said `stack expects a non-empty TensorList`. After looking into the sampled domains, it seems some domains with 1 batch left were sampled while there was no `batch_index` actually. 

Could you help look into this issue? Thank you very much.

Best, Andrew

**Comment by YugeTen** [comment]
Hey Andrew,

Thank you! I have trained the model end to end on `civilcomments` and did not encounter such a problem. May I ask

1. Which version of WILDS are you using (should be 1.1.0)?
2. Did you use the default config file in `src/config.py`?

**Comment by LFhase** [comment]
Hi Yuge,

Thanks for your reply! I indeed was using `src/config.py` but not WILDS 1.1.0 (2.0.0 instead), so I guess it's because of some update in WILDS 2.0.0. BTW I was trying to fix it by adding
```python
for i,l in enumerate(train_loader.dataset.batches_left.values()):
    Ls[i] = l>1
```
after line 87 of `utils.py`, but it will affect the performance.

Anyways, I have no further questions. Thank you again for the nice work 🐟 !
